# config-server/src/main/resources/application.yml
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LakhiniVoshadee/Smart-Parking-Management-System--SPMS-.git
          clone-on-start: true